### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by Pledix** [InventivetalentDev/PacketListenerAPI#24]
## What steps will reproduce the problem?  
1. startup

## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.7.2

## What Spigot version are you using? *Type /version*
git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
(This is a final build for 1.12.2)

## What plugins are you using? *Type /plugins*
PacketListenerApi, MapManager, Vault, ProtocolSupport, AnimatedFrames, ViaVersion, ProtocolLib

## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*
https://pastebin.com/cjv1HgEv

## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well* 
No

## Additional information?  *(Are you using Bungeecord? Did it work in previous versions? etc.)*
No

**Comment by Th3Shadowbroker** [comment]
Hi @Pledix,
I've tried to reproduce your problem using the same server version and plugins. It looks like these problems are caused by ProtocolSupport. ~~I'll try to figure out where this problem comes from.~~

Edit: Okay I read the logs and found this line:
`[ViaVersion] Hooking into ProtocolSupport, to prevent issues!`
before PacketListenerAPI is even loaded. So ProtocolSupport classes might get loaded, before PacketListenerAPI. However, this cannot be reconciled with PacketListenerAPIs loadbefore directive in its plugin.yml. It's also interesting, that ViaVersion has PacketListenerAPI as a soft-dependency which normally should prevent this kind of problem (through plugin internal handling). Neverthenless I'm definitivly not an expert for spigots dependency management and the behavior of the other dependants and...well it's just a suspicion from my side 🤔 .

**Comment by austinstiefel** [comment]
@Th3Shadowbroker @InventivetalentDev I am having this same exact error message on my server console. Will this affect the server in any way and if so how does it affect it?

**Comment by InventivetalentDev** [comment]
@Veltzkree this error shouldn't affect your server in any way, unless one of your plugins specifically depends on "pre-login" packets that are sent/received before a player has joined the server.
