### ISSUE TITLE
Add ViaVersion Support?

### ISSUE THREAD

**Issue by ghost** [InventivetalentDev/PacketListenerAPI#3]
Could you add support for the ViaVersion? (https://www.spigotmc.org/resources/viaversion.19254/)

Because when I come in 1.10, says: "Unsupported protocol version 210"

Please.

**Comment by InventivetalentDev** [comment]
That message is nothing sent by PacketListenerAPI. I have tried multiple plugins that depend on the API on servers with ViaVersion, and they worked without issues.

**Comment by ghost** [comment]
When the PacketListenerAPI + ViaVersion + ProtocolSupport, are together, the error happens.

However, you can review the support for the ProtocolSupport?

Version: 1.8 (v1_8_R3)

(just a note: when using the/skinclear command, (NickNamer) nick on tab, stay invisible.)

**Comment by InventivetalentDev** [comment]
As I said, PacketListenerAPI does not send that error. Please open an issue for ViaVersion/Protocol support, since it's probably caused by those.  

> [NickNamer issue tracker](https://github.com/InventivetalentDev/NickNamer/issues)

**Comment by FormallyMyles** [comment]
@Kurimatzu Could you try with just ProtocolSupport and see if the issue happens with PS + PacketListener? 

Without ProtocolSupport, ViaVersion has full compatibility with this API. (Possibly providing your server startup log might give us more insight, but from the looks of things it causes ProtocolSupport to override Via)

This probably isn't easily fixable unfortunate due to how aggressive protocol support is with netty injection. (it's most likely not a bug with PacketListenerAPI)

**Comment by ghost** [comment]
The problem is the packetlistenerAPI Yes, because when I use the ProtocolSupport + ViaVersion, doesn't happen the error.

**Comment by FormallyMyles** [comment]
@Kurimatzu Have you tried with just ProtocolSupport + PacketListenerAPI?

**Comment by Kurimatzu** [comment]
OPS, sorry, actually the problem is in protocolsupport.
Now I have to find another plugin to support the 1.7.
I'm sorry.

**Comment by Kurimatzu** [comment]
The ProtocolSupport was adding support to the 1.8.8, for that was the mistake.

**Comment by ghost** [comment]
Yes, the problem continues.
