### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by ItzRonaldMLG** [InventivetalentDev/PacketListenerAPI#82]
## What steps will reproduce the problem?  
1. Put plugin in plugins folder
2. Start the server

## What were you expecting to happen? What happened instead?  
It didnt start the plugin
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
3.8.0-snapshot
## What Spigot version are you using? *Type /version*  
1.16.5
## What plugins are you using? *Type /plugins*  
Also using protocollib 
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
Startup error: https://pastebin.com/YV5wzQgn

Greats,
Ronald

**Comment by Pretoreaner** [comment]
The problem is explained in line 3

org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: org/inventivetalent/packetlistener/PacketListenerPlugin has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Plugin needs runtime version 53 but java is runtime version 52

FYI

45 = Java 1.1
46 = Java 1.2
47 = Java 1.3
48 = Java 1.4
49 = Java 5
50 = Java 6
51 = Java 7
**52 = Java 8** <--- serverversion
**53 = Java 9** <--- Plugin needs
54 = Java 10
55 = Java 11
56 = Java 12
57 = Java 13

and here (https://www.spigotmc.org/resources/api-packetlistenerapi.2930/update?update=387205) you can read that Java9+ is recommended now
